name = "staroverlay-uploads-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# ======================
# PRODUCTION (default)
# ======================
[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "staroverlay-uploads-bucket"

# ======================
# DEVELOPMENT
# ======================
[env.development]
name = "uploads-worker-dev"

[env.development.vars]
ENVIRONMENT = "development"

[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "staroverlay-uploads-bucket-dev"